access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:
      uri: mongodb+srv://hello:1234@assingmentpaf.njxkken.mongodb.net/AssingmentPAF?retryWrites=true&w=majority
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
